### ISSUE TITLE
Error when opening two files with same filename

### ISSUE THREAD

**Issue by marhub** [jcupitt/php-vips-ext#5]
I have strange error, not sure it it's caused by extension or libvips, and if you will be able to reproduce it.
First - the code i'm using for narrowing the problem:

```php
$originalFile = $path."gun.jpg";
		$resultFile = $uploadPath."result-clean.jpg";

		$image = \Jcupitt\Vips\Image::newFromFile($originalFile);
		$image->writeToFile($resultFile);

		header("Content-Type: image/jpg");
		echo file_get_contents($resultFile);
```

steps to reproduce:

1. create file gun.jpg in $path
2. run once this script
3. result-clean.jpg will be created
4. modify gun.jpg ( for example add  some line in paint ).
5. remove result-clean.jpg
6. re-run this script - result-clean.jpg will be created, however copied from gun.jpg BEFORE modification

when you will change source filename, and re run, modified version will be used.

It looks like there is some kind of cache storing loaded files (?).
I'm using nginx and php-fpm. Restarting fpm "clears" this "cache" ( so new file is used ).

Any ideas ?

**Comment by marhub** [comment]
edit: restarting fpm causes more weird behaviour - in one request i see file before modifications, and next one with modifications.

**Comment by marhub** [comment]
And - if someone struggles like i do with this issue - it can be easlily resolved with 
```php
		$image = \Jcupitt\Vips\Image::newFromBuffer(file_get_contents($originalFile));
```
however it's temporary solution

**Comment by jcupitt** [comment]
Hi @marhub, yes, vips assumes files are immutable and does a lot of caching. 

You have a couple of alternatives to loading via a buffer:

1. You can turn off the caching with [`Vips\Config::cacheSetMaxFiles()`](https://jcupitt.github.io/php-vips/docs/classes/Jcupitt.Vips.Config.html#method_cacheSetMaxFiles). You'll see a slowdown if you do many operations on the same file (for example, making a series of thumbnails of various sizes). 

2. Always use unique filenames. I suppose this depends how your files are named, but it might be possible. Note that the entire path is tested, so `a/b/fred.jpg` is different from `a/c/fred.jpg`, so just appending a request ID to a temporary directory might be enough. 

3. There has been some talk of getting vips to automatically remove files from cache it it detects a change, but it's not happened yet, unfortunately. See for example #432, though that's slightly different.

**Comment by jcupitt** [comment]
You can see the caching working like this:

```
$ php -a
Interactive shell

php > require __DIR__ . '/vendor/autoload.php';
php > $x = \Jcupitt\Vips\Image::newFromFile("/data/john/pics/wtc.jpg");
php >
```

Here `wtc.jpg` is a 10k x 10k jpg image. Even so, the prompt comes back immediately, because vips is delaying pixel decode until the decoded bytes are really needed. Now try:

```
php > echo $x->avg();
117.84864125648
php >
```

This will trigger decode and find the average pixel value. You'll see a pause of about a second before the prompt comes back. Try the echo again and you'll find you get the answer immediately: vips has cached the load and also the find-average operation.

Now free the image and reload:

```
php > $x = nil;
php > $x = \Jcupitt\Vips\Image::newFromFile("/data/john/pics/wtc.jpg");
php >
```

As before, the load is instant. In fact, behind the scenes, vips hasn't delayed the load, it's actually reused the old result. Now try:

```
php > echo $x->avg();
117.84864125648
php >
```

You'll find you get the answer immediately, even though the image has apparently changed.
